version: '1'
  
services:

  backend:
    container_name: frontend
    image: idk

    ports:
      - "80:8080"  

  backend:
    container_name: backend
    image: idk

    ports:
      - "80:9000"

    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb

    volumes:
      - wordpress:/var/www/html

    volumes: 
      - db:/var/lib/mysql